import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Aside from './components/Aside';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Inventory Application',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Aside />
        <div className='content'>
        {children}
        </div>
      </body>
    </html>
  );
}
